"""Remove check constraint for check_quantity_positive

Revision ID: 4cecc45fb898
Revises: 774c7c792b59
Create Date: 2024-09-12 08:09:50.794582

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cecc45fb898"
down_revision: Union[str, None] = "774c7c792b59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
