"""Return total field for Product table

Revision ID: 278f3047f3f3
Revises: 4cecc45fb898
Create Date: 2024-09-12 08:25:43.996513

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "278f3047f3f3"
down_revision: Union[str, None] = "4cecc45fb898"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "total")
    # ### end Alembic commands ###
